//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESTION_REPUESTOS.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class CompraRepuesto
    {
        public int CompraRepuestoID { get; set; }
        public Nullable<int> CompraID { get; set; }
        public Nullable<int> RepuestoID { get; set; }
        public int Cantidad { get; set; }
        public decimal PrecioUnitario { get; set; }
        [JsonIgnore]
        public virtual Compra Compra { get; set; }
        [JsonIgnore]
        public virtual Repuesto Repuesto { get; set; }
    }
}
