//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESTION_REPUESTOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpleadoCargo
    {
        public string EmpleadoID { get; set; }
        public int CargoID { get; set; }
        public System.DateTime FechaAsignacion { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
