//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESTION_REPUESTOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Garantia
    {
        public int GarantiaID { get; set; }
        public Nullable<int> FacturaID { get; set; }
        public Nullable<int> TipoGarantiaID { get; set; }
        public System.DateTime FechaInicio { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual TipoGarantia TipoGarantia { get; set; }
    }
}
